export const FILED_TYPES = {
  PASSWORD: 'password',
  USER_NAME: 'userName',
  MOBILE_NUMBER: 'mobileNo',
  ALPHA_NUMERIC: 'alphaNumeric',
  ADDRESS: 'address',
  NUMERIC: 'numeric',
  STATUS: 'status',
  DECIMAL: 'decimal',
  COLOR: 'color',
  DATE: 'date',
  DATETIME: 'datetime',
  FORMER_DATETIME: 'formerDateTime',
  LANDLINE: 'landline',
  IS_NOT_EMPTY: 'isNotEmpty',
  EMAIL: 'email',
};
